import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

import Footer from "./Component/Footer1";
import Navbar from "@/app/Component/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Go Trip",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display:'swap',
  fallback: ['Arial', 'sans-serif'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
 
      <body className={montserrat.className}>
      
      {/* <Navbar/>*/} 
        {children}
        <Footer/>
        </body>
    </html>
  );
}
