import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./Component/Footer1";
import Navbar from "@/app/Component/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Go Trip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body >
      
      {/* <Navbar/>*/} 
        {children}
        <Footer/>
        </body>
    </html>
  );
}
